### ISSUE TITLE
SOFT: Test infinite tracking. FPS printed a 0, motors doesn't run again, track lost although one light is on...

### ISSUE THREAD

**Issue by poketecop** [poketecop/MyLoyalFilmer#22]
Countours: 13

Color x: 254 y: 7 width: 386 height: 437

Countours: 11

Color x: 239 y: 0 width: 401 height: 406

Center x: 439.5

Center y: 203.0

Move clockwise: 10 degrees.

Raw angles: x = 70 y = 90

Safe angles: x = 70 y = 90

Current angles: x = 80 y = 90

Current servo pulse x: 80

Servo pulse x: 70

Countours: 20

Color x: 153 y: 0 width: 487 height: 453

Countours: 33

Color x: 244 y: 0 width: 396 height: 452

Center x: 442.0

Center y: 226.0

Move clockwise: 10 degrees.

Raw angles: x = 60 y = 90

Safe angles: x = 60 y = 90

Current angles: x = 70 y = 90

Current servo pulse x: 70

Servo pulse x: 60

Countours: 14

Color x: 175 y: 0 width: 465 height: 423

Countours: 32

Color x: 221 y: 0 width: 419 height: 439

Center x: 430.5

Center y: 219.5

Move clockwise: 10 degrees.

Raw angles: x = 50 y = 90

Safe angles: x = 50 y = 90

Current angles: x = 60 y = 90

Current servo pulse x: 60

Servo pulse x: 50

Countours: 15

Color x: 121 y: 0 width: 519 height: 476

Countours: 37

Color x: 246 y: 0 width: 394 height: 423

Center x: 443.0

Center y: 211.5

Move clockwise: 10 degrees.

Raw angles: x = 40 y = 90

Safe angles: x = 40 y = 90

Current angles: x = 50 y = 90

Current servo pulse x: 50

Servo pulse x: 40

Countours: 41

Color x: 141 y: 0 width: 499 height: 465

Countours: 32

Color x: 143 y: 0 width: 497 height: 428

Center x: 391.5

Center y: 214.0

Countours: 11

Color x: 113 y: 0 width: 527 height: 457

Countours: 40

Color x: 105 y: 0 width: 535 height: 475

Center x: 372.5

Center y: 237.5

Countours: 30

Color x: 87 y: 0 width: 553 height: 480

Countours: 11

Color x: 141 y: 0 width: 499 height: 480

Center x: 390.5

Center y: 240.0

Countours: 28

Color x: 136 y: 0 width: 504 height: 475

Countours: 3

Color x: 187 y: 0 width: 453 height: 451

Center x: 413.5

Center y: 225.5

Move clockwise: 10 degrees.

Raw angles: x = 30 y = 90

Safe angles: x = 30 y = 90

Current angles: x = 40 y = 90

Current servo pulse x: 40

Servo pulse x: 30

Countours: 3

Color x: 180 y: 0 width: 460 height: 422

Countours: 13

Color x: 164 y: 0 width: 476 height: 423

Center x: 402.0

Center y: 211.5

Countours: 19

Color x: 317 y: 0 width: 323 height: 365

Countours: 3

Color x: 256 y: 0 width: 384 height: 396

Center x: 448.0

Center y: 198.0

Move clockwise: 10 degrees.

Raw angles: x = 20 y = 90

Safe angles: x = 20 y = 90

Current angles: x = 30 y = 90

Current servo pulse x: 30

Servo pulse x: 20

Countours: 2

Color x: 223 y: 0 width: 417 height: 395

Countours: 16

Color x: 300 y: 0 width: 340 height: 369

Center x: 470.0

Center y: 184.5

Move clockwise: 10 degrees.

Raw angles: x = 10 y = 90

Safe angles: x = 10 y = 90

Current angles: x = 20 y = 90

Current servo pulse x: 20

Servo pulse x: 10

Countours: 21

Color x: 161 y: 0 width: 479 height: 371

Countours: 46

Color x: 216 y: 0 width: 424 height: 377

Center x: 428.0

Center y: 188.5

Move clockwise: 10 degrees.

Raw angles: x = 0 y = 90

Safe angles: x = 0 y = 90

Current angles: x = 10 y = 90

Current servo pulse x: 10

Servo pulse x: 0

Countours: 44

Color x: 113 y: 0 width: 527 height: 380

Countours: 59

Color x: 106 y: 0 width: 534 height: 381

Center x: 373.0

Center y: 190.5

Countours: 68

Color x: 111 y: 0 width: 529 height: 380

Countours: 84

Color x: 267 y: 0 width: 373 height: 323

Center x: 453.5

Center y: 161.5

Move clockwise: 10 degrees.

Raw angles: x = -10 y = 90

Safe angles: x = -10 y = 90

Current angles: x = 0 y = 90

Current servo pulse x: 0

Servo pulse x: -10

Move up: 10 degrees.

Raw angles: x = -10 y = 100

Safe angles: x = -10 y = 100

Current angles: x = -10 y = 90

Current servo pulse y: 90

Servo pulse y: 100

Countours: 89

Color x: 200 y: 200 width: 372 height: 263

Countours: 105

Color x: 218 y: 186 width: 348 height: 276

Center x: 392.0

Center y: 324.0

Countours: 106

Color x: 233 y: 210 width: 350 height: 256

Countours: 112

Color x: 233 y: 212 width: 351 height: 252

Center x: 408.5

Center y: 338.0

Countours: 112

Color x: 233 y: 212 width: 351 height: 252

Countours: 113

Color x: 234 y: 207 width: 351 height: 256

Center x: 409.5

Center y: 335.0

Countours: 111

Color x: 237 y: 211 width: 348 height: 254

Countours: 115

Color x: 239 y: 225 width: 325 height: 238

Center x: 401.5

Center y: 344.0

Countours: 122

Color x: 239 y: 235 width: 321 height: 231

Countours: 120

Color x: 236 y: 212 width: 348 height: 253

Center x: 410.0

Center y: 338.5

Move clockwise: 10 degrees.

Raw angles: x = -20 y = 100

Safe angles: x = -10 y = 100

Current angles: x = -10 y = 100

Countours: 111

Color x: 238 y: 230 width: 329 height: 233

Countours: 117

Color x: 237 y: 223 width: 336 height: 240

Center x: 405.0

Center y: 343.0

Countours: 117

Color x: 237 y: 223 width: 336 height: 240

Countours: 107

Color x: 237 y: 223 width: 328 height: 240

Center x: 401.0

Center y: 343.0

Countours: 112

Color x: 234 y: 210 width: 352 height: 253

Countours: 108

Color x: 234 y: 225 width: 331 height: 238

Center x: 399.5

Center y: 344.0

Countours: 112

Color x: 237 y: 227 width: 330 height: 236

Countours: 94

Color x: 241 y: 230 width: 325 height: 233

Center x: 403.5

Center y: 346.5

Countours: 108

Color x: 241 y: 228 width: 327 height: 235

Countours: 103

Color x: 237 y: 232 width: 325 height: 231

Center x: 399.5

Center y: 347.5

Countours: 103

Color x: 237 y: 232 width: 325 height: 231

Countours: 104

Color x: 239 y: 229 width: 323 height: 234

Center x: 400.5

Center y: 346.0

Countours: 110

Color x: 239 y: 216 width: 343 height: 249

Countours: 97

Color x: 237 y: 233 width: 323 height: 230

Center x: 398.5

Center y: 348.0

Countours: 102

Color x: 237 y: 232 width: 323 height: 231

Countours: 109

Color x: 239 y: 214 width: 345 height: 249

Center x: 411.5

Center y: 338.5

Move clockwise: 10 degrees.

Raw angles: x = -20 y = 100

Safe angles: x = -10 y = 100

Current angles: x = -10 y = 100

Countours: 88

Color x: 237 y: 232 width: 319 height: 231

Countours: 102

Color x: 359 y: 247 width: 281 height: 228

Center x: 499.5

Center y: 361.0

Move clockwise: 10 degrees.

Raw angles: x = -20 y = 100

Safe angles: x = -10 y = 100

Current angles: x = -10 y = 100

Move down: 10 degrees.

Raw angles: x = -10 y = 90

Safe angles: x = -10 y = 90

Current angles: x = -10 y = 100

Current servo pulse y: 100

Servo pulse y: 90

Countours: 95

Color x: 237 y: 107 width: 355 height: 246

Countours: 77

Color x: 238 y: 94 width: 359 height: 247

Center x: 417.5

Center y: 217.5

Move clockwise: 10 degrees.

Raw angles: x = -20 y = 90

Safe angles: x = -10 y = 90

Current angles: x = -10 y = 90

Countours: 90

Color x: 234 y: 96 width: 359 height: 247

Countours: 90

Color x: 234 y: 96 width: 359 height: 247

Center x: 413.5

Center y: 219.5

Move clockwise: 10 degrees.

Raw angles: x = -20 y = 90

Safe angles: x = -10 y = 90

Current angles: x = -10 y = 90

Countours: 91

Color x: 233 y: 97 width: 357 height: 245

Countours: 94

Color x: 235 y: 97 width: 338 height: 246

Center x: 404.0

Center y: 220.0

Countours: 87

Color x: 234 y: 95 width: 359 height: 249

Countours: 86

Color x: 232 y: 95 width: 362 height: 249

Center x: 413.0

Center y: 219.5

Move clockwise: 10 degrees.

Raw angles: x = -20 y = 90

Safe angles: x = -10 y = 90

Current angles: x = -10 y = 90

Countours: 88

Color x: 178 y: 0 width: 413 height: 345

Countours: 94

Color x: 175 y: 0 width: 419 height: 345

Center x: 384.5

Center y: 172.5

Countours: 94

Color x: 175 y: 0 width: 419 height: 345

Countours: 80

Color x: 175 y: 0 width: 419 height: 345

Center x: 384.5

Center y: 172.5

Countours: 86

Color x: 188 y: 0 width: 406 height: 344

Countours: 84

Color x: 175 y: 0 width: 415 height: 345

Center x: 382.5

Center y: 172.5

Countours: 81

Color x: 175 y: 0 width: 418 height: 344

Countours: 92

Color x: 175 y: 0 width: 416 height: 344

Center x: 383.0

Center y: 172.0

Countours: 81

Color x: 176 y: 0 width: 418 height: 343

Countours: 97

Color x: 176 y: 0 width: 406 height: 345

Center x: 379.0

Center y: 172.5

Countours: 88

Color x: 176 y: 0 width: 405 height: 343

Countours: 89

Color x: 187 y: 0 width: 380 height: 343

Center x: 377.0

Center y: 171.5

Countours: 82

Color x: 193 y: 47 width: 384 height: 296

Countours: 90

Color x: 177 y: 0 width: 382 height: 345

Center x: 368.0

Center y: 172.5

Countours: 92

Color x: 175 y: 0 width: 390 height: 343

Countours: 93

Color x: 174 y: 0 width: 387 height: 344

Center x: 367.5

Center y: 172.0

Countours: 84

Color x: 175 y: 3 width: 400 height: 339

Countours: 80

Color x: 176 y: 0 width: 409 height: 344

Center x: 380.5

Center y: 172.0

Countours: 78

Color x: 178 y: 0 width: 402 height: 345

Countours: 88

Color x: 176 y: 0 width: 399 height: 344

Center x: 375.5

Center y: 172.0

Countours: 88

Color x: 176 y: 0 width: 399 height: 344

Countours: 76

Color x: 176 y: 0 width: 382 height: 343

Center x: 367.0

Center y: 171.5

Countours: 89

Color x: 176 y: 0 width: 385 height: 346

Countours: 75

Color x: 177 y: 0 width: 391 height: 343

Center x: 372.5

Center y: 171.5

Countours: 91

Color x: 177 y: 0 width: 396 height: 344

Countours: 84

Color x: 176 y: 0 width: 385 height: 342

Center x: 368.5

Center y: 171.0

Countours: 94

Color x: 175 y: 0 width: 385 height: 344

Countours: 83

Color x: 177 y: 0 width: 398 height: 345

Center x: 376.0

Center y: 172.5

Countours: 73

Color x: 177 y: 0 width: 392 height: 343

Countours: 91

Color x: 177 y: 0 width: 384 height: 343

Center x: 369.0

Center y: 171.5

Countours: 77

Color x: 178 y: 0 width: 383 height: 345

Countours: 78

Color x: 178 y: 13 width: 375 height: 330

Center x: 365.5

Center y: 178.0

Countours: 82

Color x: 176 y: 0 width: 370 height: 344

Countours: 83

Color x: 178 y: 0 width: 352 height: 343

Center x: 354.0

Center y: 171.5

Countours: 80

Color x: 176 y: 0 width: 347 height: 344

Countours: 81

Color x: 175 y: 0 width: 371 height: 345

Center x: 360.5

Center y: 172.5

Countours: 63

Color x: 175 y: 0 width: 350 height: 344

Countours: 82

Color x: 163 y: 0 width: 416 height: 345

Center x: 371.0

Center y: 172.5

Countours: 82

Color x: 163 y: 0 width: 416 height: 345

Countours: 82

Color x: 163 y: 0 width: 362 height: 346

Center x: 344.0

Center y: 173.0

Countours: 71

Color x: 149 y: 0 width: 423 height: 344

Countours: 76

Color x: 155 y: 0 width: 394 height: 344

Center x: 352.0

Center y: 172.0

Countours: 75

Color x: 177 y: 0 width: 368 height: 345

Countours: 82

Color x: 175 y: 0 width: 352 height: 344

Center x: 351.0

Center y: 172.0

Countours: 70

Color x: 156 y: 0 width: 409 height: 346

Countours: 79

Color x: 149 y: 0 width: 369 height: 343

Center x: 333.5

Center y: 171.5

Countours: 80

Color x: 157 y: 0 width: 370 height: 343

Countours: 89

Color x: 178 y: 0 width: 347 height: 345

Center x: 351.5

Center y: 172.5

Countours: 92

Color x: 148 y: 5 width: 374 height: 341
The video capturing was released

Reading videoCapture finish.

FPS: 23.78400716109355

 Color track finish.
^[[B^[[B^[[B^[[B^[[B^[[B^[[A^[[A^[[AThe video was successfully saved

Save film finished.

 Entered color_track method.

Raw angles: x = 90 y = 90

Safe angles: x = 90 y = 90

Current angles: x = -10 y = 90

Current servo pulse x: -10

Servo pulse x: 90

About to start...

Raw angles: x = 160 y = 80

Safe angles: x = 160 y = 80

Current angles: x = 90 y = 90

Current servo pulse x: 90

Servo pulse x: 160

Current servo pulse y: 90

Servo pulse y: 80

Servos initial position set.

Film capture initied.

Film saving resolution: 640 X 480

Tue_25_01_2022_01_24_43

Film saving initied.

Color track start: 1643045083.659993

 Color track finish.The video was successfully saved

Save film finished.

The video capturing was released

Reading videoCapture finish.

FPS: 0.0
^[[B^[[B^[[B^[[B
consecutive_tracking_option_times: 100000

track_lost_consecutive_times: 100000

Track lost

 Entered color_track method.

Raw angles: x = 90 y = 90

Safe angles: x = 90 y = 90

Current angles: x = 160 y = 80

Current servo pulse x: 160

Servo pulse x: 90

Current servo pulse y: 80

Servo pulse y: 90

Raw angles: x = 160 y = 80

About to start...

Safe angles: x = 160 y = 80

Current angles: x = 90 y = 90

Current servo pulse x: 90

Servo pulse x: 160

Current servo pulse y: 90

Servo pulse y: 80

Servos initial position set.

Film capture initied.

Film saving resolution: 640 X 480

Tue_25_01_2022_01_25_31

Film saving initied.

Color track start: 1643045131.0595455

 Color track finish.
The video was successfully saved

Save film finished.
The video capturing was released

Reading videoCapture finish.

FPS: 0.0
^[^C
*** Finish ***
Traceback (most recent call last):
  File "Yahboom_Project/MyLoyalFilmer/src/main.py", line 22, in <module>
    sys.exit(main(sys.argv[1:]))  # next section explains the use of sys.exit
  File "Yahboom_Project/MyLoyalFilmer/src/main.py", line 17, in main
    robot.play()
  File "/home/pi/Yahboom_Project/MyLoyalFilmer/src/model/robot/RobotModule.py", line 128, in play
    self.infinite_track_line_and_color_track()
  File "/home/pi/Yahboom_Project/MyLoyalFilmer/src/model/robot/RobotModule.py", line 148, in infinite_track_line_and_color_track
    self.track_line_and_color_track()
  File "/home/pi/Yahboom_Project/MyLoyalFilmer/src/model/robot/RobotModule.py", line 162, in track_line_and_color_track
    self.track_line()
  File "/home/pi/Yahboom_Project/MyLoyalFilmer/src/model/robot/RobotModule.py", line 270, in track_line
    self.motors.right()
  File "/home/pi/Yahboom_Project/MyLoyalFilmer/src/model/robot/MotorsModule.py", line 125, in right
    def right(self):
KeyboardInterrupt
pi@yahboomtank:~ $

**Comment by poketecop** [comment]
Tracking problems fixed. Now we have to solve following filming not working. Make simple test of two consecutive filmings to test it.
